grafana:
  ingress:
    enabled: true
    hosts: 
      - grafana.pf2e.io
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
    tls: 
    - secretName: argocd-secret # do not change, this is provided by Argo CD
      hosts:
        - grafana.pf2e.io
  rbac:
    pspEnabled: false
    pspUseAppArmor: false
