apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: default
spec:
  encryptedData:
    admin-password: AgCpQ08owK3EbDCUut/zqcfjBssoXBan+bHgUTtRgzTCH3z3IoZha8SeZqdtGwK4Cv7rkjC5bZXxwX82/pNSfxTrHIIXaiEmoepeQe8jZ50fFMh/if59LcgBaNLHPHv7VFyfn5IGZ0i4DOSpNJg7QfWZcZXoDCpIcn/mobx70FYlB4JJtp8H3kIqwxmkSib5RxYVnpo6iaD14ufdS3sdqMVPnSlXwIY3pQWCnI1TFYGTzOTAINTMipb+0MenJ3AiRFR4aUvumuMRHrPalXWG+4pMIIEyXdVE91fKDvOOFNPtWgv2OPke3BLXZWWcI51RZrQB/hD84lkPz9Tl+w7qQhe63x8qptTrzFzurypftFYT3NgvNrpRXQ5R2hdbvigI2F+F4sUQvUy/ZEpwBju4Q+P2yB8JRVK1kooirRlJypx7IGLPAzkVvmPwbY4rUOc7ZeFmFRTgLVl89KuXtgI04MIuuQA/rcmw7MH6o4334thcDSua0+Ew2AJb/nsJfhufgqPv6b3DaiY1WEeoGvFQZ/oZuBHQNoCUoMwXuqI56QfcY2X5sVc6NqkVBayZz4JomK8bgQL8Fsq85M3JNbVrGK5fHotX59XA/yrOqrKTEgokfNi/mdac5F6o9Lx7wg5j7j5tchcmuntHbY6k0Sc77JquCNm5SamLJFfIEtElYFlDedVC0dF/haG1BeckHGh/FXdrMHEzhMMdyRsDK3/e
    admin-user: AgCoB/bguFK/CfQcLOqkb/5zE11d11K1pcoyfIJmT0j1Cng+zoA9MtcrJyNIzajEjBrUOt7p/ylZ83qQeQnici2S4IeF3NymjuFIU3Fjz+iVu5SMOmH+aTrEpPVykyKf80ClDnVpwouiu/NATKe2WWHO6FOCa8CEfo/SY0nQY0eF71joFccUZ+QuA+JengbROzpnmmXUpPECxsaLHKOwJQS0Td8ohfLp9dzDy/ZhDkWNnXtWnBKGrcfZX3Tc7xRq/pLYMQLh48Rv9eYsIXW81LiJDtLkmgFtQYcMs3NurqnhSv9g//KDJMQYDhzBPhTk2K6TKEkFT2BZRU5pZFg9BGTen1NrdwwVVxoc8X90ES5ZZD9ubzCucWflJQ80ZIUB6ssT5lhzqBAssRMF53DGi7dXh/tjBchJEu+5DP+uUzNT2d2f/p0Mk2NEg92pVHA+plY9JcvF/floexcwTaLQM+mSu0GbM4Dj2fkzjPW7ofm5Sfdket4T+6/s93OZ6mgdcHq5sXFYawmywIYWllQZh9VhsQfUHdPRKTtSVxJJkRvR/gn6jhS79illStEoxbJJJgP2zC/I6ZLz3wHt2+1ViC/bzj5qPoPgaKRSWHShKvp583fM8wAnsqhmZOgFsBc5CuTN9kW1BPNLMOR0s6OLLm06CKDNNDYglWqIhrqy/+g2GGY0hmhmtPuPbKlmIxfHbQnBweF143mFmHnmHtVEhPCoRrN5C0eGQg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: default
    type: Opaque

