apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
  - secretKey: admin-user
    remoteRef:
      key: silvester-io_grafana_username
  - secretKey: admin-password
    remoteRef:
      key: silvester-io_grafana_password