apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCPFGpPmEW3uS37PjcF0CrLnoQoRMb6vg5CvR0Qn1580qdJQhc0vrYcEaU1xwn62uTRox+R8jlZeED2phdaulRnLD9belAbqsxwZKtcyZ7MjOatcroMbBBIwvnitXOsyTJYACBdq7xXRmDEk5szmE19u+dOF3J7P4p00F8EiUhEv5TzT8E+VYVx3vsIEk/QkM9f9ZEHL/Y4LSACZYWDSVlheEcC9KSXwZqvcTSxyaE0SuXaRrAAxWOOTExtOI4L+bp6dLCCIlBICNniySHPAyXVgblckuDPfBvNI/pdpJ3E+Low8KakSBcNXaCmsfc2TJmWP74gT7FedfC5OiKaWPdtqtKI+cV5hk5mA80TFLwE497zbBFw0JxgnETfitcnf1GKpEVn3twTvhiJWMfrcWYQOFvVVMHQ2V5I5a4HermQm2BN4cLUz9lJWjBFdQmS7rttwyAXmrdgDD9x8mXDB8w5pzkCZdmVHl2C8t2zHdSaOPx89nUA8jBAoiuaPd5CeIpQU3wZcljsIzMiLqXbEJamE4h8XNePrzt5qyCtpOsWdsqCOB7KIiyoJpp97j/nFaUxdTKbjiQASnr1wJ6n7X3BtPCCFrj6DyUYxZJcA8LGkyPcXsMZUEA/Lf3bJUWimQ1Emn1KhZ2Kbt0b1EOSKTiIoHu8GFxaqZsYBh4fJX31fNXw01oJrkz0AFhIKE9MGcaa0u6IYYeux9GO3lQA
    admin-user: AgABoIj9U0VKzS3alpbrmVUb2GHMZ2KkaRPsToj7taTfdId7nk3CE7KycNGV3ynQm6ikNQhqG4JAKrfXOEjVSOx4d8STOBX8s1XKwbDMpATDNo6Xh6dSWhSKp4gOxtNEVfwBwx1Wbh9/KNYkHGybWA83WFnDpbu0Bw4ady2Jv5F3WDEuEG7rdhpHY1sPUaoFziULNUsonTmW3ykRnIZjt7zlsOpJZEK9/kU1KCTyzNYCAYngtay3QsBfVm7NwNXR9ocCkMLKpul0hLsYlII8fknYiWonFPHOlMV5GLujxSu3QSD9ifm1epoLoFVCIZuM/IhPvtLAz1PBg756JGzq4qY3vrAF2FI4iNkDd1MapL39ZFMxYN9WjvWi3eFT8YofPJ+4WHyQ0zbxPBMzHE/BFjPNrK11Xx+oz1231Uh5byh2PuupQ9VfnEE5B1T9iqfU5w3OdGgrSAX7MS2fYJsqOrWDcuJHZye9VEvC/1KFO+KMWtAW/VtyHs4K682fABKuDqdkXwst25VxQqrZPSfcGfC4Nb8tb0OrzX4CM13rkFbnjydVS8D9Mu7OvMafzEEqWNCKSJYrxotUY2ST9OUO75UU4OVBjaVZhDaMn6GTjdGUY+8Q6DZ6Yu05g55sE/gyVb5cInkVTQvw7I05fkH3mkriRxBjSkSxbftEJe0H65NMzCtOare8W0kvlku6xB2ZRximpwT5+XKNIX2cEryhXCT+BE5SjANMMQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring
    type: Opaque

