apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBuutEdc+zQyFKQm1FtqMhxBZShwufUEoIYiuj0ZhYgltSzV9Tv6kHNyLmuh2Jb38sFiFFzNO75M9PqqgFmDFWb609+UVXpS0aZnXmfcY9+pwhdcdSGCsDR1OIEZT/WCyaTLrD+sGC9kxm+ObUYlo4jSTStHpTx93a+7IbgJA2mM86oNiEGwie4EEGplPkeXstnnewRcQRvz4XxrjIgFBgvcuohrtdEs1cop6+c5+etuSvF55Vciwt8/gfI7IB/2IfvVi1c5nKKutnKPSXuwzesrzOYAJdE9jenHwJLX1rIHhwx8Rg2kwIH3i+kZyQlLh3xXNEs6t9jvaL4HN12TyO1H609B/a36DHN0BsWzmwnCf3ZxJZ+wG3dEuuTakHnAYYLaS589WXk+DquH02n7k7SHINscfzgmgSb6P4WrTbMDjx3OQh0Ya3kR0pkL7AGcHzPjsX+FuRryVClsjLPro7OjCI60ttiP7jpzVe4+6j0HDnTnnnxRqc32GptYLX7l9jz1x3v23hqV8tWHajr/8EOLeG1pVEK1wPY9bbxgeCY3ZT+rAU2vzV7sjtSYHJgfiuL0sqovGmtbb62K588ojJWysl1WHq66DAg0uuddRqBmlR+4rvsjjZme2gLR5GGQm8LzVN/qv4Q8tHnaK2oU9MV/HOFsH4GXgkqTTHQzNEUmHNY6/6XnFax0i5MoRVzKkCeQ+31eOSQrxuuu8bM
    admin-user: AgCxfbjWgwDVPoIXP3pvuthovmnDQ1E3HS87esJCgD5yjB9/GYZB6STvvtMl6ciHjmFkwgTOyg95JfhVhYKjOZS0rfR+tRiRhI5PY4VMS/wTazKt9WtINeI03N1qeKLfuTVWfGf2pUl79EhAxQgw2eOkrtZa0gNm1e/KLJtyl8bNlmPHUytph0sgOIMHWLX5RG9bxMN9FE6ZkgqiAgzK2nEIsXYA4m+KXQu1h5TrrucK5vM4jirVlC34AN4p2K758hZim2w4xXwCc//mhOakXWbxpQKMwRksjVVBgGf0ryQpVq7jINhDbRPfdY+kIt5JZECCVyz4aY1WHuJpChPRX9i76d/jvrJh455YrAZWSnyA1s2FKx9pDwX2nUAk31coD1tI9aQHjqJqECG1+KupIo4jknw4aHXJ1leiWt2z5gdj9Rj4gtn58Xw8Ekc9Hn3F84jueXaorvhiN3wGUh05InLB3LFFZSrxoXSSorMLWKXUmX93Tej3DH02mGEtdVQY/zlNgcn3EOMBLB3T9bT5BA8S3826SyAQoC6h2QAVoJ3v6SabV5r8fOdXFr6tOSl+Ino9HQDtWxoQs3YNM/3K+XAwvYgvaflIpKjPl96/D9cneO/B32oaFh/sg72BGahAiBVssxMljze1OOjEr7y7mCorYpHqWBVenBrCzkQ+YvXL7d3qdK4x+uLAesOVRsVYRrPzAw66nR8WbQ3TFSdMBQGSvjnLX7CuOQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring
    type: Opaque

